Header header
string[] name
float64[] desiredPosition
float64[] desiredPositionVelocityLimit
float64[] feedForwardTorque
float64[] proportionalGain
float64[] derivativeGain
float64[] integralGain
float64[] positionLoopTorqueLimit
float64[] positionLoopWindupLimit
float64[] torqueLoopVelocityLimit

string FULL           =full
string GRAVITY        =gravity
string INERTIA        =inertia
string NONE           =none
